###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    memcached:
      image: memcached:alpine
      container_name: reapractive-backend-memcached

    redis:
      image: redis:alpine
      container_name: reapractive-backend-redis

    postgres:
      image: postgres:11.1-alpine
      container_name: reapractive-backend-postgres
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - POSTGRES_USER=root
        - POSTGRES_PASSWORD=reapractive
        - POSTGRES_DB=reapractive
      ports:
        - "8084:5432"

    webserver:
      image: nginx:alpine
      container_name: reapractive-backend-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8080:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: reapractive-backend-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini

