#index:
#    path: /
#    controller: App\Controller\DefaultController::index
check:
  path: /check
  controller: App\Controller\CheckController::index
  methods: GET
user_data_index:
  path: /user_data
  controller: App\Controller\UserDataController::index
  methods: GET
user_data_create:
  path: /user_data/create
  controller: App\Controller\UserDataController::createUserData
  methods: POST
